name: playx_widget
description: Playx Package that contains utility widgets.
version: 0.0.2
homepage: https://sourcya.com/
repository: https://github.com/playx-flutter/playx_widget

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.2.3
  package_info_plus: ^4.0.0
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
