name: playx_widget
description: Playx Package that contains utility widgets as it contains common widgets and utilities that are needed in each project .
version: 0.1.3
homepage: https://sourcya.com/
repository: https://github.com/playx-flutter/playx_widget
issue_tracker: https://github.com/playx-flutter/playx_widget/issues
topics:
  - playx
  - widgets
  - ui

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  flutter_platform_widgets: ^6.1.0
  wolt_modal_sheet: ^0.5.0
  flutter_keyboard_visibility: ^6.0.0
  sliver_tools: ^0.2.12
  dotted_border: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
